### ISSUE TITLE
Track Timer Extension Usage/Timer Stocks Taken

### ISSUE THREAD

**Issue by TranquilRuhe** [JettJengaGod/scoresheetbot#39] opened 2020-12-25 01:43 UTC
Being able to properly note when a crew has used their 5 minute extension, as well as being able to put in when a player loses a stock from timer. ,timerext and ,timerstock would be my suggested commands.

**Comment by JettJengaGod** [comment] 2020-12-25 02:27
Partial duplicate of https://github.com/JettJengaGod/scoresheetbot/issues/29

**Closed as completed** 2020-12-26 21:39 UTC
